services:
  - type: web
    name: petstore-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: petstore-db
          property: connectionString
      - key: APP_CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: petstore-frontend
          property: url

  - type: web
    name: petstore-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: petstore-backend
          property: url
        append: /galang/v1

databases:
  - name: petstore-db
    plan: free
