services:
  - type: web
    name: petstore-backend
    runtime: docker
    plan: free
    rootDir: backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: petstore-db
          property: connectionString
      - key: APP_CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: petstore-frontend
          property: host

  - type: web
    name: petstore-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: petstore-backend
          property: host
        append: /galang/v1

databases:
  - name: petstore-db
    plan: free
